### ISSUE TITLE
Acess to pbf file header and file metrics

### ISSUE THREAD

**Issue by fschutt** [TeXitoi/osmpbfreader-rs#11]
These are a few issues I noticed when working with osmpbfreader:

1. There is no access to the header block - the [HeaderBlock](https://docs.rs/osmpbfreader/0.11.1/osmpbfreader/osmformat/struct.HeaderBlock.html) is defined, but cannot be accessed in any way. Which is sad, because it contains the timestamp when this pbf file was made (otherwise, I'd have to rely on the file timestamp, which can be a bit later).

2. It would be nice to expose more file metrics, mainly for the use in memory-mapped files. Memory-mapped files cannot implement `Read` (as far as I know). Memory mapping basically means having two references to the start and the length of a file, instead of holding a file descriptor. This increases performance because you don't have to tell the OS "get me the file" on each read, you just give it an adress. Which puts less stress on the CPU. Now, how osmpfbreader comes into play: Every memory-map implementation needs a start index (in bytes) and a length, that you want to read into RAM. PBF files can be decoded into self-contained blobs of 32MB max (according to the OSM Wiki). What I wanted to do is to memory-map a file and then load several fileblocks, so I don't exceed a given memory limit. However, I am missing the metrics, especially the offset from the start of the file. I found out that you can compute the length of the blob with [compute_size()](https://docs.rs/osmpbfreader/0.11.1/osmpbfreader/fileformat/struct.Blob.html#method.compute_size), but I could not figure out how to get the offset from the start of the file or how to get the individual blob, not load the whole file. So I had to fall back on regular files.

3. Parallel iteration is currently only possible on all objects. However, generally you already know that you only want certain types (node, way or relation). It would be nice to have a way to access only relations for example and then have a parallel iterator on that. I currently have an implementation that looks like this: https://github.com/sharazam/osmpg/blob/master/src/osm_pbf.rs#L96-L102
I am not very proud of the code structure, but it reduces the iteration from 26 seconds to 9 seconds for a 150MB file.

**Comment by TeXitoi** [comment]
1. OK, I'll look how I can give access to the Header.

2. I don't get the idea you're trying to do. Mmapped files are interesting when you seek randomly in the file and can reference directly addresses inside the file to memory. But pbf is a stream format: You must read the files in order, and it's almost always compressed, thus you need to decode to memory (and you thus can't reference directly to the mmapped addresses).

3. OK, I'll see how I can give the ability to easily construct your iterator by type with easy parallelism. Note that I'll be surprised if `pat_iter` is not faster than you version in your case as there is much less relations than nodes and ways and your version decode/uncompress the protobuf 3 times instead of 1 time (and that's the most costy operation).

**Comment by sharazam** [comment]
2. PBF is a stream format, but .osm.pbf is a bit special - you have 16 - 32MiB blobs. Each blob is decodable on it's own. So basically what I wanted to do was to load 4 or 8 (user configurable) blobs à 32MB from the memmapped adress into a temporary buffer. This way I don't have to load the whole file. Then decode each fileblock on it's own and push relevant stuff into a node / way memory buffer. The maximum memory usage would be 8x32MiB).

3. Misunderstanding. `par_iter` currently goes through the whole file while my version only goes through the `groups::dense_nodes` for example. Yes there is decompression, but `par_iter` decompresses, too (blobs.rs, line 54). But `par_iter` goes through literally every node and checks if it is a node (in `result_blob_into_iter`) and then checks. While my version operates at the primitivegroup level and discards the whole primitivegroup if it is not a (node | way | relation). Because OSM 

`blob > primitivegroup > (node | way | relation)`

I have to check way less, plus I don't risk any false positives. From the OSM Wiki site: "A PrimitiveGroup MUST NEVER contain different types of objects." - so this is why I only check the primitivegroup. I'll post performance results if I get to it.

I thought this could be solved with an enum on `par_iter`: 
```rust
pub enum OSMType {
    Node,
    Way,
    Relation,
}

pub fn par_iter<'a>(&'a mut self, predicate: OSMType) -> ParIter<'a, R> {
    /* handle sparse - dense nodes*/
    ParIter(self.blobs()
                .filter(|x| x.unwrap().get_primitivegroup()
                .filter(|y| /* use predicate here*/ y.dense_nodes()))
                .collect()
                .par_flat_map(result_blob_into_iter))
}
```

Where dense_nodes would return references to the primitivegroups densenodes struct. Not tested in any way, just an idea

**Comment by TeXitoi** [comment]
2. that's basically what's doing `par_iter`
3. you're calling `primitive_block_from_blob` 3 times, that's about 75% of the time spent by osmpbreader (the others 25% are creating the `OsmObj`). I don't get your "I don't have to check every nodes", you're doing that in the 2 other threads.

I don't get your "I have to check 8K times less than par_iter", `iter` and `par_iter` do the same thing. You're reading the nodes in the other threads. And calling `group::ways` on a group without ways is almost free.

**Comment by TeXitoi** [comment]
Closed because no returns.
